openapi: 3.2.0
info:
  title: GLS Netherlands LabelApi - Production Delivery API
  description: GLS Label API Production environment
  version: v1
servers:
- url: https://api.gls.nl/v1
tags:
- name: Delivery
paths:
  /api/Label/Create:
    post:
      tags:
      - Delivery
      summary: CreateLabel
      operationId: CreateLabel
      parameters:
      - name: api-version
        in: query
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/InboundCreateDeliveryRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              customerNo: string
              customerSubjectName: string
              reference: string
              trackingLinkType: u
              units:
              - unitId: string
                unitType: co
                customerUnitReference: string
                weight: 0
                dimensions:
                  length: 0
                  width: 0
                  height: 0
                additionalInfo1: string
                additionalInfo2: string
              labelType: zpl
              labelA4StartPosition: 0
              labelA4MoveXMm: 0
              labelA4MoveYMm: 0
              notificationEmail:
                sendMail: true
                senderName: string
                senderReplyAddress: string
                senderContactName: string
                senderPhoneNo: string
                emailSubject: string
                emailAddressCC: string
                emailAddressBCC: string
              returnRoutingData: true
              addresses:
                pickupAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                deliveryAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                  addresseeType: b
              shippingDate: string
              services:
                addresseeOnlyService: true
                expressService: none
                expressConfirmSMS: string
                economyParcel: true
                letterBoxParcel: true
                shopDeliveryService: true
                shopDeliveryParcelShopId: string
                shopDeliveryPlusService: true
                shopReturnService: true
                saturdayService: true
          application/json:
            schema:
              $ref: '#/components/schemas/InboundCreateDeliveryRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              customerNo: string
              customerSubjectName: string
              reference: string
              trackingLinkType: u
              units:
              - unitId: string
                unitType: co
                customerUnitReference: string
                weight: 0
                dimensions:
                  length: 0
                  width: 0
                  height: 0
                additionalInfo1: string
                additionalInfo2: string
              labelType: zpl
              labelA4StartPosition: 0
              labelA4MoveXMm: 0
              labelA4MoveYMm: 0
              notificationEmail:
                sendMail: true
                senderName: string
                senderReplyAddress: string
                senderContactName: string
                senderPhoneNo: string
                emailSubject: string
                emailAddressCC: string
                emailAddressBCC: string
              returnRoutingData: true
              addresses:
                pickupAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                deliveryAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                  addresseeType: b
              shippingDate: string
              services:
                addresseeOnlyService: true
                expressService: none
                expressConfirmSMS: string
                economyParcel: true
                letterBoxParcel: true
                shopDeliveryService: true
                shopDeliveryParcelShopId: string
                shopDeliveryPlusService: true
                shopReturnService: true
                saturdayService: true
          text/json:
            schema:
              $ref: '#/components/schemas/InboundCreateDeliveryRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              customerNo: string
              customerSubjectName: string
              reference: string
              trackingLinkType: u
              units:
              - unitId: string
                unitType: co
                customerUnitReference: string
                weight: 0
                dimensions:
                  length: 0
                  width: 0
                  height: 0
                additionalInfo1: string
                additionalInfo2: string
              labelType: zpl
              labelA4StartPosition: 0
              labelA4MoveXMm: 0
              labelA4MoveYMm: 0
              notificationEmail:
                sendMail: true
                senderName: string
                senderReplyAddress: string
                senderContactName: string
                senderPhoneNo: string
                emailSubject: string
                emailAddressCC: string
                emailAddressBCC: string
              returnRoutingData: true
              addresses:
                pickupAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                deliveryAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                  addresseeType: b
              shippingDate: string
              services:
                addresseeOnlyService: true
                expressService: none
                expressConfirmSMS: string
                economyParcel: true
                letterBoxParcel: true
                shopDeliveryService: true
                shopDeliveryParcelShopId: string
                shopDeliveryPlusService: true
                shopReturnService: true
                saturdayService: true
          application/*+json:
            schema:
              $ref: '#/components/schemas/InboundCreateDeliveryRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              customerNo: string
              customerSubjectName: string
              reference: string
              trackingLinkType: u
              units:
              - unitId: string
                unitType: co
                customerUnitReference: string
                weight: 0
                dimensions:
                  length: 0
                  width: 0
                  height: 0
                additionalInfo1: string
                additionalInfo2: string
              labelType: zpl
              labelA4StartPosition: 0
              labelA4MoveXMm: 0
              labelA4MoveYMm: 0
              notificationEmail:
                sendMail: true
                senderName: string
                senderReplyAddress: string
                senderContactName: string
                senderPhoneNo: string
                emailSubject: string
                emailAddressCC: string
                emailAddressBCC: string
              returnRoutingData: true
              addresses:
                pickupAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                deliveryAddress:
                  name1: string
                  name2: string
                  name3: string
                  street: string
                  houseNo: string
                  houseNoExt: string
                  zipCode: string
                  city: string
                  countryCode: string
                  contact: string
                  phone: string
                  email: string
                  addresseeType: b
              shippingDate: string
              services:
                addresseeOnlyService: true
                expressService: none
                expressConfirmSMS: string
                economyParcel: true
                letterBoxParcel: true
                shopDeliveryService: true
                shopDeliveryParcelShopId: string
                shopDeliveryPlusService: true
                shopReturnService: true
                saturdayService: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCreateLabelResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
                shipmentTrackingLink: string
                labels: string
                units:
                - {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '422':
          description: Unprocessable Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '424':
          description: Failed Dependency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
  /api/Label/Delete:
    post:
      tags:
      - Delivery
      summary: DeleteLabel
      operationId: DeleteLabel
      parameters:
      - name: api-version
        in: query
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/InboundDeleteRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
          application/json:
            schema:
              $ref: '#/components/schemas/InboundDeleteRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
          text/json:
            schema:
              $ref: '#/components/schemas/InboundDeleteRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/InboundDeleteRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiDeleteLabelResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '424':
          description: Failed Dependency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
  /api/Label/Confirm:
    post:
      tags:
      - Delivery
      summary: ConfirmLabel
      operationId: ConfirmLabel
      parameters:
      - name: api-version
        in: query
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/InboundConfirmRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
              shippingDate: string
          application/json:
            schema:
              $ref: '#/components/schemas/InboundConfirmRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
              shippingDate: string
          text/json:
            schema:
              $ref: '#/components/schemas/InboundConfirmRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
              shippingDate: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/InboundConfirmRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNo: string
              shippingDate: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiConfirmLabelResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '424':
          description: Failed Dependency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
  /api/Label/ConfirmMultiple:
    post:
      tags:
      - Delivery
      summary: ConfirmMultiple
      operationId: ConfirmMultiple
      parameters:
      - name: api-version
        in: query
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/InboundConfirmMultipleRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNos:
              - string
              shippingDate: string
          application/json:
            schema:
              $ref: '#/components/schemas/InboundConfirmMultipleRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNos:
              - string
              shippingDate: string
          text/json:
            schema:
              $ref: '#/components/schemas/InboundConfirmMultipleRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNos:
              - string
              shippingDate: string
          application/*+json:
            schema:
              $ref: '#/components/schemas/InboundConfirmMultipleRequest'
            example:
              username: string
              password: string
              shippingSystemName: string
              shippingSystemVersion: string
              shiptype: p
              unitNos:
              - string
              shippingDate: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiConfirmLabelResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
        '424':
          description: Failed Dependency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
              example:
                error: true
                status: string
                message: string
                errors: {}
                transactionId: string
components:
  schemas:
    ExpressServiceType:
      enum:
      - none
      - t9
      - t10
      - t12
      - t17
      - s9
      - s10
      - s12
      - s17
      type: string
    DeliveryAddress:
      required:
      - city
      - countryCode
      - name1
      - street
      - zipCode
      type: object
      properties:
        name1:
          maxLength: 30
          minLength: 1
          type: string
        name2:
          maxLength: 30
          type:
          - string
          - 'null'
        name3:
          maxLength: 30
          type:
          - string
          - 'null'
        street:
          maxLength: 40
          minLength: 1
          type: string
        houseNo:
          maxLength: 5
          type:
          - string
          - 'null'
        houseNoExt:
          maxLength: 5
          type:
          - string
          - 'null'
        zipCode:
          maxLength: 8
          minLength: 1
          type: string
        city:
          maxLength: 30
          minLength: 1
          type: string
        countryCode:
          maxLength: 2
          minLength: 1
          type: string
        contact:
          maxLength: 30
          type:
          - string
          - 'null'
        phone:
          maxLength: 25
          type:
          - string
          - 'null'
        email:
          maxLength: 320
          type:
          - string
          - 'null'
        addresseeType:
          $ref: '#/components/schemas/AdresseeType'
      additionalProperties: false
    ApiConfirmLabelResponseObject:
      type: object
      properties:
        error:
          type: boolean
          readOnly: true
        status:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
        errors:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: string
        transactionId:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    Services:
      type: object
      properties:
        addresseeOnlyService:
          type:
          - boolean
          - 'null'
        expressService:
          $ref: '#/components/schemas/ExpressServiceType'
        expressConfirmSMS:
          type:
          - string
          - 'null'
        economyParcel:
          type:
          - boolean
          - 'null'
        letterBoxParcel:
          type:
          - boolean
          - 'null'
        shopDeliveryService:
          type:
          - boolean
          - 'null'
        shopDeliveryParcelShopId:
          type:
          - string
          - 'null'
        shopDeliveryPlusService:
          type:
          - boolean
          - 'null'
        shopReturnService:
          type:
          - boolean
          - 'null'
        saturdayService:
          type:
          - boolean
          - 'null'
      additionalProperties: false
    LabelResultType:
      enum:
      - zpl
      - zplUtf8
      - zpl300
      - zpl300Utf8
      - pdf
      - pdfRoutingOnly
      - zplRoutingOnly
      - zplUtf8RoutingOnly
      - zpl300RoutingOnly
      - zpl300Utf8RoutingOnly
      - pdfA6U
      - pdfA6S
      - pdf2A4
      - pdf4A4
      - none
      type: string
    Unit:
      required:
      - unitId
      - weight
      type: object
      properties:
        unitId:
          maxLength: 50
          minLength: 1
          type: string
        unitType:
          $ref: '#/components/schemas/UnitType'
        customerUnitReference:
          maxLength: 35
          type:
          - string
          - 'null'
        weight:
          type: number
          format: float
        dimensions:
          $ref: '#/components/schemas/Dimensions'
        additionalInfo1:
          maxLength: 30
          type:
          - string
          - 'null'
        additionalInfo2:
          maxLength: 30
          type:
          - string
          - 'null'
      additionalProperties: false
    TrackingLinkType:
      enum:
      - u
      - s
      type: string
    NotificationEmail:
      type: object
      properties:
        sendMail:
          type:
          - boolean
          - 'null'
        senderName:
          maxLength: 30
          type:
          - string
          - 'null'
        senderReplyAddress:
          maxLength: 320
          type:
          - string
          - 'null'
        senderContactName:
          maxLength: 30
          type:
          - string
          - 'null'
        senderPhoneNo:
          maxLength: 25
          type:
          - string
          - 'null'
        emailSubject:
          maxLength: 50
          type:
          - string
          - 'null'
        emailAddressCC:
          maxLength: 320
          type:
          - string
          - 'null'
        emailAddressBCC:
          maxLength: 320
          type:
          - string
          - 'null'
      additionalProperties: false
    ShipType:
      enum:
      - p
      - f
      type: string
    ApiCreateLabelResponseObject:
      type: object
      properties:
        error:
          type: boolean
          readOnly: true
        status:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
        errors:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: string
        transactionId:
          type:
          - string
          - 'null'
          format: uuid
        shipmentTrackingLink:
          type:
          - string
          - 'null'
        labels:
          type:
          - string
          - 'null'
        units:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ApiUnit'
      additionalProperties: false
    InboundDeleteRequest:
      required:
      - password
      - unitNo
      - username
      type: object
      properties:
        username:
          maxLength: 70
          minLength: 1
          type: string
        password:
          maxLength: 20
          minLength: 1
          type: string
          writeOnly: true
        shippingSystemName:
          type:
          - string
          - 'null'
        shippingSystemVersion:
          type:
          - string
          - 'null'
        shiptype:
          $ref: '#/components/schemas/ShipType'
        unitNo:
          maxLength: 14
          minLength: 1
          type: string
      additionalProperties: false
    InboundConfirmMultipleRequest:
      required:
      - password
      - unitNos
      - username
      type: object
      properties:
        username:
          maxLength: 70
          minLength: 1
          type: string
        password:
          maxLength: 20
          minLength: 1
          type: string
          writeOnly: true
        shippingSystemName:
          type:
          - string
          - 'null'
        shippingSystemVersion:
          type:
          - string
          - 'null'
        shiptype:
          $ref: '#/components/schemas/ShipType'
        unitNos:
          type: array
          items:
            type: string
        shippingDate:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    ApiDeleteLabelResponseObject:
      type: object
      properties:
        error:
          type: boolean
          readOnly: true
        status:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
        errors:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: string
        transactionId:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    PickupAddress:
      required:
      - city
      - countryCode
      - name1
      - street
      - zipCode
      type: object
      properties:
        name1:
          maxLength: 30
          minLength: 1
          type: string
        name2:
          maxLength: 30
          type:
          - string
          - 'null'
        name3:
          maxLength: 30
          type:
          - string
          - 'null'
        street:
          maxLength: 40
          minLength: 1
          type: string
        houseNo:
          maxLength: 5
          type:
          - string
          - 'null'
        houseNoExt:
          maxLength: 5
          type:
          - string
          - 'null'
        zipCode:
          maxLength: 8
          minLength: 1
          type: string
        city:
          maxLength: 30
          minLength: 1
          type: string
        countryCode:
          maxLength: 2
          minLength: 1
          type: string
        contact:
          maxLength: 30
          type:
          - string
          - 'null'
        phone:
          maxLength: 25
          type:
          - string
          - 'null'
        email:
          maxLength: 320
          type:
          - string
          - 'null'
      additionalProperties: false
    AdresseeType:
      enum:
      - b
      - p
      type: string
    UnitType:
      enum:
      - co
      - lg
      - mp
      - bp
      - xl
      - pl
      - rl
      type: string
    InboundConfirmRequest:
      required:
      - password
      - unitNo
      - username
      type: object
      properties:
        username:
          maxLength: 70
          minLength: 1
          type: string
        password:
          maxLength: 20
          minLength: 1
          type: string
          writeOnly: true
        shippingSystemName:
          type:
          - string
          - 'null'
        shippingSystemVersion:
          type:
          - string
          - 'null'
        shiptype:
          $ref: '#/components/schemas/ShipType'
        unitNo:
          maxLength: 14
          minLength: 1
          type: string
        shippingDate:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    ApiResponseObject:
      type: object
      properties:
        error:
          type: boolean
          readOnly: true
        status:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
        errors:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - array
            - 'null'
            items:
              type: string
        transactionId:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    DeliveryAddresses:
      type: object
      properties:
        pickupAddress:
          $ref: '#/components/schemas/PickupAddress'
        deliveryAddress:
          $ref: '#/components/schemas/DeliveryAddress'
      additionalProperties: false
    ApiUnit:
      type: object
      additionalProperties: false
    InboundCreateDeliveryRequest:
      required:
      - password
      - username
      type: object
      properties:
        username:
          maxLength: 70
          minLength: 1
          type: string
        password:
          maxLength: 20
          minLength: 1
          type: string
          writeOnly: true
        shippingSystemName:
          type:
          - string
          - 'null'
        shippingSystemVersion:
          type:
          - string
          - 'null'
        shiptype:
          $ref: '#/components/schemas/ShipType'
        customerNo:
          maxLength: 8
          minLength: 7
          type:
          - string
          - 'null'
        customerSubjectName:
          maxLength: 50
          type:
          - string
          - 'null'
        reference:
          maxLength: 20
          type:
          - string
          - 'null'
        trackingLinkType:
          $ref: '#/components/schemas/TrackingLinkType'
        units:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Unit'
        labelType:
          $ref: '#/components/schemas/LabelResultType'
        labelA4StartPosition:
          type:
          - integer
          - 'null'
          format: int32
        labelA4MoveXMm:
          type:
          - integer
          - 'null'
          format: int32
        labelA4MoveYMm:
          type:
          - integer
          - 'null'
          format: int32
        notificationEmail:
          $ref: '#/components/schemas/NotificationEmail'
        returnRoutingData:
          type: boolean
        addresses:
          $ref: '#/components/schemas/DeliveryAddresses'
        shippingDate:
          type:
          - string
          - 'null'
          format: date-time
        services:
          $ref: '#/components/schemas/Services'
      additionalProperties: false
    Dimensions:
      type: object
      properties:
        length:
          type: integer
          format: int32
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
      additionalProperties: false
